default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: db_6lni_user
  password: ffjLlRajW0VnOw2DVYJzx6fLwIuDS5jW
  host: dpg-csjjr4e8ii6s73d4thgg-a.oregon-postgres.render.com
  port: <%= ENV['DB_PORT'] || 5432 %>

development:
  <<: *default
  database: db_6lni

test:
  <<: *default
  database: db_6lni

production:
  <<: *default
  database: db_6lni
